
void makeEffMergedFiles(const TString& infile) {
  TFile *file = TFile::Open(infile, "UPDATE");
  TH1D * eff = file->Get("h_ptb_eff")->Clone("eff");
  eff->Divide(h_ptb_num, h_ptb_den, 1.0, 1.0, "B");
  eff->Write();
  TH1D * eff_ht1 = file->Get("h_ptb_num_ht1")->Clone("eff_ht1");
  eff_ht1->Divide(h_ptb_num_ht1, h_ptb_den_ht1, 1.0, 1.0, "B");
  eff_ht1->Write();
  TH1D * eff_ht2 = file->Get("h_ptb_num_ht2")->Clone("eff_ht2");
  eff_ht2->Divide(h_ptb_num_ht2, h_ptb_den_ht2, 1.0, 1.0, "B");
  eff_ht2->Write();
  TH1D * eff_ht3 = file->Get("h_ptb_num_ht3")->Clone("eff_ht3");
  eff_ht3->Divide(h_ptb_num_ht3, h_ptb_den_ht3, 1.0, 1.0, "B");
  eff_ht3->Write();
  eff->Write();
  TH1D * eff_ht2GeV1 = file->Get("h_ptb_num_ht2GeV1")->Clone("eff_ht2GeV1");
  eff_ht2GeV1->Divide(h_ptb_num_ht2GeV1, h_ptb_den_ht2GeV1, 1.0, 1.0, "B");
  eff_ht2GeV1->Write();
  TH1D * eff_ht2GeV2 = file->Get("h_ptb_num_ht2GeV2")->Clone("eff_ht2GeV2");
  eff_ht2GeV2->Divide(h_ptb_num_ht2GeV2, h_ptb_den_ht2GeV2, 1.0, 1.0, "B");
  eff_ht2GeV2->Write();
  TH1D * eff_ht2GeV3 = file->Get("h_ptb_num_ht2GeV3")->Clone("eff_ht2GeV3");
  eff_ht2GeV3->Divide(h_ptb_num_ht2GeV3, h_ptb_den_ht2GeV3, 1.0, 1.0, "B");
  eff_ht2GeV3->Write();
  TH1D * eff_htGenJet1 = file->Get("h_ptb_num_htGenJet1")->Clone("eff_htGenJet1");
  eff_htGenJet1->Divide(h_ptb_num_htGenJet1, h_ptb_den_htGenJet1, 1.0, 1.0, "B");
  eff_htGenJet1->Write();
  TH1D * eff_htGenJet2 = file->Get("h_ptb_num_htGenJet2")->Clone("eff_htGenJet2");
  eff_htGenJet2->Divide(h_ptb_num_htGenJet2, h_ptb_den_htGenJet2, 1.0, 1.0, "B");
  eff_htGenJet2->Write();
  TH1D * eff_htGenJet3 = file->Get("h_ptb_num_htGenJet3")->Clone("eff_htGenJet3");
  eff_htGenJet3->Divide(h_ptb_num_htGenJet3, h_ptb_den_htGenJet3, 1.0, 1.0, "B");
  eff_htGenJet3->Write();
  TH1D * eff_htChPF1 = file->Get("h_ptb_num_htChPF1")->Clone("eff_htChPF1");
  eff_htChPF1->Divide(h_ptb_num_htChPF1, h_ptb_den_htChPF1, 1.0, 1.0, "B");
  eff_htChPF1->Write();
  TH1D * eff_htChPF2 = file->Get("h_ptb_num_htChPF2")->Clone("eff_htChPF2");
  eff_htChPF2->Divide(h_ptb_num_htChPF2, h_ptb_den_htChPF2, 1.0, 1.0, "B");
  eff_htChPF2->Write();
  TH1D * eff_htChPF3 = file->Get("h_ptb_num_htChPF3")->Clone("eff_htChPF3");
  eff_htChPF3->Divide(h_ptb_num_htChPF3, h_ptb_den_htChPF3, 1.0, 1.0, "B");
  eff_htChPF3->Write();
  TH1D * eff_ht1w = file->Get("h_ptb_num_ht1w")->Clone("eff_ht1w");
  eff_ht1w->Divide(h_ptb_num_ht1w, h_ptb_den_ht1w, 1.0, 1.0, "B");
  eff_ht1w->Write();
  TH1D * eff_ht2w = file->Get("h_ptb_num_ht2w")->Clone("eff_ht2w");
  eff_ht2w->Divide(h_ptb_num_ht2w, h_ptb_den_ht2w, 1.0, 1.0, "B");
  eff_ht2w->Write();
  TH1D * eff_ht3w = file->Get("h_ptb_num_ht3w")->Clone("eff_ht3w");
  eff_ht3w->Divide(h_ptb_num_ht3w, h_ptb_den_ht3w, 1.0, 1.0, "B");
  eff_ht3w->Write();
  TH1D * effhtS1 = file->Get("h_htS1_eff")->Clone("effhtS1");
  effhtS1->Divide(h_htS1_num, h_htS1_den, 1.0, 1.0, "B");
  effhtS1->Write();
  TH1D * effhtS3 = file->Get("h_htS3_eff")->Clone("effhtS2");
  effhtS3->Divide(h_htS3_num, h_htS3_den, 1.0, 1.0, "B");
  effhtS3->Write();
  TH1D * effW1 = file->Get("h_ptb_numW1")->Clone("effW1");
  effW1->Divide(h_ptb_numW1, h_ptb_denW1, 1.0, 1.0, "B");
  effW1->Write();
  TH1D * effWHT = file->Get("h_ptb_numWHT")->Clone("effWHT");
  effWHT->Divide(h_ptb_numWHT, h_ptb_denWHT, 1.0, 1.0, "B");
  effWHT->Write();
  TH1D * effWHT25 = file->Get("h_ptb_numWHT25")->Clone("effWHT25");
  effWHT25->Divide(h_ptb_numWHT25, h_ptb_denWHT25, 1.0, 1.0, "B");
  effWHT25->Write();
  TH1D * effWHTB = file->Get("h_ptb_numWHTB")->Clone("effWHTB");
  effWHTB->Divide(h_ptb_numWHTB, h_ptb_denWHTB, 1.0, 1.0, "B");
  effWHTB->Write();
  TH1D * effWHTB25 = file->Get("h_ptb_numWHTB25")->Clone("effWHTB25");
  effWHTB25->Divide(h_ptb_numWHTB25, h_ptb_denWHTB25, 1.0, 1.0, "B");
  effWHTB25->Write();
  TH1D * eff05 = file->Get("h_ptb05_eff")->Clone("eff05");
  eff05->Divide(h_ptb05_num, h_ptb05_den, 1.0, 1.0, "B");
  eff05->Write();
  TH1D * effiso = file->Get("h_ptbiso_eff")->Clone("effiso");
  effiso->Divide(h_ptbiso_num, h_ptbiso_den, 1.0, 1.0, "B");
  effiso->Write();
  TH1D * effisojet = file->Get("h_ptbisojet_eff")->Clone("effisojet");
  effisojet->Divide(h_ptbisojet_num, h_ptbisojet_den, 1.0, 1.0, "B");
  effisojet->Write();
  TH1D * effisojet40 = file->Get("h_ptbisojet40_eff")->Clone("effisojet40");
  effisojet40->Divide(h_ptbisojet40_num, h_ptbisojet40_den, 1.0, 1.0, "B");
  effisojet40->Write();
  TH2D * effptbhtS1 = file->Get("h_ptb_htS1_eff")->Clone("effptbhtS1");
  effptbhtS1->Divide(h_ptb_htS1_num, h_ptb_htS1_den, 1.0, 1.0, "B");
  effptbhtS1->Write();
  TH2D * effptbhtS3 = file->Get("h_ptb_htS3_eff")->Clone("effptbhtS3");
  effptbhtS3->Divide(h_ptb_htS3_num, h_ptb_htS3_den, 1.0, 1.0, "B");
  effptbhtS3->Write();
//  TH2D * effptbx1x2 = file->Get("h_ptb_x1x2_eff")->Clone("effptbx1x2");
//  effptbx1x2->Divide(h_ptb_x1x2_num, h_ptb_x1x2_den, 1.0, 1.0, "B");
//  effptbx1x2->Write();
  file->Close();

}
