root -b -q 'simpleComparePlots.C("h_nvtx_eff", "Isolation Efficiency vs NPV")' 
root -b -q 'simpleComparePlots.C("h_fake_el_iso_cor", "RelIso (0.3) for Fakes (EB)")' 
root -b -q 'simpleComparePlots.C("h_true_el_iso_cor", "RelIso (0.3) for True (EB)")' 
root -b -q 'simpleComparePlots.C("h_fakeEE_el_iso_cor", "RelIso (0.3) for Fakes (EE)")' 
root -b -q 'simpleComparePlots.C("h_trueEE_el_iso_cor", "RelIso (0.3) for True (EE)")' 
root -b -q 'simpleComparePlots.C("h_nvtx_fr", "Isolation Fake Rate vs NPV")' 
